In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
data = np.random.randn(4,3)

In [4]:
data

array([[-0.91907343,  0.43534133, -0.59853643],
       [-0.15109834,  0.26800484,  1.32777821],
       [ 0.50412844, -0.1895572 , -0.52168295],
       [ 1.74014073,  2.07149779, -1.3645012 ]])

In [5]:
data_frame=pd.DataFrame(data)

In [6]:
data_frame

          0         1         2
0 -0.919073  0.435341 -0.598536
1 -0.151098  0.268005  1.327778
2  0.504128 -0.189557 -0.521683
3  1.740141  2.071498 -1.364501

In [7]:
new_df=pd.DataFrame(data,index=["Batu","John","Atlas","Max"], columns=["Salary","Age","Seniority"])

In [8]:
new_df

         Salary       Age  Seniority
Batu  -0.919073  0.435341  -0.598536
John  -0.151098  0.268005   1.327778
Atlas  0.504128 -0.189557  -0.521683
Max    1.740141  2.071498  -1.364501

In [10]:
new_df.loc["Batu"]

Salary      -0.919073
Age          0.435341
Seniority   -0.598536
Name: Batu, dtype: float64

In [11]:
new_df["Extra"]=10

In [12]:
new_df

         Salary       Age  Seniority  Extra
Batu  -0.919073  0.435341  -0.598536     10
John  -0.151098  0.268005   1.327778     10
Atlas  0.504128 -0.189557  -0.521683     10
Max    1.740141  2.071498  -1.364501     10

In [15]:
new_df.drop("Extra", axis=1)

         Salary       Age  Seniority
Batu  -0.919073  0.435341  -0.598536
John  -0.151098  0.268005   1.327778
Atlas  0.504128 -0.189557  -0.521683
Max    1.740141  2.071498  -1.364501

In [16]:
new_df

         Salary       Age  Seniority  Extra
Batu  -0.919073  0.435341  -0.598536     10
John  -0.151098  0.268005   1.327778     10
Atlas  0.504128 -0.189557  -0.521683     10
Max    1.740141  2.071498  -1.364501     10

In [17]:
new_df.drop("Extra",axis=1,inplace=True)

In [18]:
new_df

         Salary       Age  Seniority
Batu  -0.919073  0.435341  -0.598536
John  -0.151098  0.268005   1.327778
Atlas  0.504128 -0.189557  -0.521683
Max    1.740141  2.071498  -1.364501

In [20]:
new_df["Mehmet"]=10

In [22]:
new_df

         Salary       Age  Seniority  Mehmet
Batu  -0.919073  0.435341  -0.598536      10
John  -0.151098  0.268005   1.327778      10
Atlas  0.504128 -0.189557  -0.521683      10
Max    1.740141  2.071498  -1.364501      10

In [24]:
new_df.drop("Mehmet", axis=1)

         Salary       Age  Seniority
Batu  -0.919073  0.435341  -0.598536
John  -0.151098  0.268005   1.327778
Atlas  0.504128 -0.189557  -0.521683
Max    1.740141  2.071498  -1.364501

In [25]:
#Index

In [27]:
reset_df=new_df.reset_index()

In [28]:
reset_df

   index    Salary       Age  Seniority  Mehmet
0   Batu -0.919073  0.435341  -0.598536      10
1   John -0.151098  0.268005   1.327778      10
2  Atlas  0.504128 -0.189557  -0.521683      10
3    Max  1.740141  2.071498  -1.364501      10

In [30]:
reset_df.drop(labels="Mehmet", axis=1)

   index    Salary       Age  Seniority
0   Batu -0.919073  0.435341  -0.598536
1   John -0.151098  0.268005   1.327778
2  Atlas  0.504128 -0.189557  -0.521683
3    Max  1.740141  2.071498  -1.364501